# Generated by Django 3.0.4 on 2020-03-23 02:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('enclosure', models.CharField(max_length=120)),
                ('comments', models.CharField(max_length=120)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=120)),
            ],
        ),
    ]
